export const TOGGLE_TEST = 'TOGGLE_TEST';

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const FETCH_FOOTBALLARTICLES_REQUEST = 'FETCH_FOOTBALLARTICLES_REQUEST';
export const FETCH_FOOTBALLARTICLES_SUCCESS = 'FETCH_FOOTBALLARTICLES_SUCCESS';
export const FETCH_FOOTBALLARTICLES_FAILURE = 'FETCH_FOOTBALLARTICLES_FAILURE';

export const FETCH_COOKINGARTICLES_REQUEST = 'FETCH_COOKINGARTICLES_REQUEST';
export const FETCH_COOKINGARTICLES_SUCCESS = 'FETCH_COOKINGARTICLES_SUCCESS';
export const FETCH_COOKINGARTICLES_FAILURE = 'FETCH_COOKINGARTICLES_FAILURE';

